[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["node"]

[build.nixpacks.build]
cmds = [
  "npm install --legacy-peer-deps",
  "npm run build:web"
]

[deploy]
startCommand = "npx serve dist --single --listen 3000" 