[build]
builder = "dockerfile"
dockerfilePath = "birdnet-api/dockerfile"
dockerContext = "birdnet-api"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
[services.web]
name = "birdnet-api" 